"""Train the browser-side Normal AI policy from grouped candidate features.

Input is JSON generated by export-ai-training.ts. The trainer uses only Python's
standard library and writes a compact linear softmax policy consumed by TypeScript.
"""

import argparse
import json
import math
import random
from datetime import datetime, timezone
from pathlib import Path


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("input", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--learning-rate", type=float, default=0.035)
    args = parser.parse_args()

    dataset = json.loads(args.input.read_text(encoding="utf-8"))
    positions = dataset["positions"]
    width = len(dataset["featureNames"])
    flat = [candidate["features"] for position in positions for candidate in position["candidates"]]
    means = [sum(row[i] for row in flat) / len(flat) for i in range(width)]
    scales = []
    for i in range(width):
        variance = sum((row[i] - means[i]) ** 2 for row in flat) / len(flat)
        scales.append(max(math.sqrt(variance), 1e-6))

    def normalized(row):
        return [(row[i] - means[i]) / scales[i] for i in range(width)]

    weights = [0.0] * width
    rng = random.Random(20260620)
    for epoch in range(args.epochs):
        rng.shuffle(positions)
        rate = args.learning_rate / (1 + epoch * 0.025)
        for position in positions:
            rows = [normalized(candidate["features"]) for candidate in position["candidates"]]
            scores = [sum(w * value for w, value in zip(weights, row)) for row in rows]
            ceiling = max(scores)
            exps = [math.exp(min(30, score - ceiling)) for score in scores]
            total = sum(exps)
            probabilities = [value / total for value in exps]
            chosen = position["chosenIndex"]
            for feature in range(width):
                expected = sum(probabilities[i] * rows[i][feature] for i in range(len(rows)))
                weights[feature] += rate * (rows[chosen][feature] - expected)
                weights[feature] *= 0.9999

    model = {
        "version": 1,
        "trainedAt": datetime.now(timezone.utc).isoformat(),
        "trainingGames": dataset["gameCount"],
        "trainingPositions": len(positions),
        "featureNames": dataset["featureNames"],
        "means": means,
        "scales": scales,
        "weights": weights,
        "bias": 0,
    }
    args.output.write_text(json.dumps(model, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"games": model["trainingGames"], "positions": len(positions), "weights": weights}))


if __name__ == "__main__":
    main()
